name: Prime Lens Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17229
title: Prime Lens Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dab996'
    - '#000000'
    - '#60acc8'
    - '#a06156'
  brandStrength: 0.1803759327158332
  lightness: 0.08060538838617504
  saturation: 0.7978820886928588
  rhythmicContrast: 0.7217130234930664
purpose: []
