name: Prime Lens Photography
favicon: null
layout_spectrum: 0.7367986964527518
typography_spectrum: 0.3724197051487863
title: Prime Lens Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1803759327158332
  lightness: 0.08060538838617504
  saturation: 0.7978820886928588
  rhythmicContrast: 0.7217130234930664
purpose: []
